__predict_true/false: Make these work with C++ too.
Should fix build after recent assert.h change.

error: no match for `operator!=' (operand types are `...' and `int')

PR lib/59231: assert.h: missing branch prediction